package com.mosect.smali.java.parser.node;

public enum SmaliNodeType {

    TREE_DOCUMENT,
    TREE_CLASS_ELEMENT,
    TREE_SOURCE_ELEMENT,
    TREE_SUPER_ELEMENT,
    TREE_FIELD_ELEMENT,
    TREE_METHOD_ELEMENT,
    TREE_ANNOTATION_ELEMENT,
    TREE_IMPLEMENTS_ELEMENT,

    TOKEN_ELEMENT,
    TOKEN_CLASS_PATH,
    TOKEN_KEYWORD,

    TOKEN_STRING,
    TOKEN_COMMENT,
    TOKEN_WHITESPACE,
    TOKEN_LINEFEED,
}
